 # Exception
num1=input("Enter the first number =>")

num2=input("Enter the second number =>")
 
try:
    print("Addtion is => ",int(num1)+num2)
except Exception as e:
                      print("Exception")


print("Code after the Exception ")

